import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseScript} from '../extension/metadata.js';
const nativeTools=new Map();
const context=vm.createContext({AbortController,structuredClone,crypto:{randomUUID:()=> 'document-1'},URL,location:{href:'http://localhost:17892/'},document:{title:'Demo',modelContext:{registerTool(t,{signal}){if(nativeTools.has(t.name))throw Error('duplicate');nativeTools.set(t.name,t);signal.addEventListener('abort',()=>nativeTools.delete(t.name),{once:true});}}},navigator:{},history:{pushState(_a,_b,url){context.location.href=new URL(url,context.location.href).href;},replaceState(){}},addEventListener(){},window:{postMessage(){}}});
vm.runInContext(fs.readFileSync(new URL('../extension/runtime.js',import.meta.url),'utf8'),context);
const runtime=context.WebMCPScript;
let release;
runtime.install({id:'demo',matches:['http://localhost/allowed*'],tools:[{name:'sum',description:'Sum',inputSchema:{type:'object'},execute:({a,b})=>a+b},{name:'slow',description:'Pending',inputSchema:{type:'object'},execute:()=>new Promise(r=>release=r)}]});
assert.equal(runtime.snapshot().tools.length,0);
context.history.pushState(null,'','/allowed');
assert.equal(runtime.snapshot().tools.length,2);
assert.equal(nativeTools.size,2);
const rev=runtime.snapshot().revision;
assert.equal((await runtime.request('call',{name:'demo__sum',revision:rev,input:{a:2,b:3}})).result,5);
const pending=runtime.request('call',{name:'demo__slow',revision:rev,input:{}});
await assert.rejects(runtime.request('call',{name:'demo__sum',revision:rev,input:{a:2,b:3}}),/仍在执行/);
release('done');await pending;
context.history.pushState(null,'','/other');
assert.equal(nativeTools.size,0);
context.history.pushState(null,'','/allowed');
assert.equal(nativeTools.size,2);
assert.equal((await nativeTools.get('demo__sum').execute({a:4,b:5})),9);
context.history.pushState(null,'','/other');
await assert.rejects(runtime.request('call',{name:'demo__sum',revision:rev,input:{a:2,b:3}}),/已变化/);
await runtime.request('remove',{id:'demo'});context.history.pushState(null,'','/allowed');assert.equal(runtime.snapshot().tools.length,0);
assert.equal(parseScript(fs.readFileSync(new URL('../examples/demo.source.js',import.meta.url),'utf8')).id,'local-demo');
assert.throws(()=>parseScript('// no metadata'),/元数据/);
runtime.install({id:'a__b',tools:[{name:'c',description:'A',inputSchema:{type:'object'},execute:()=>1}]});
assert.throws(()=>runtime.install({id:'a',tools:[{name:'b__c',description:'B',inputSchema:{type:'object'},execute:()=>2}]}),/名称冲突/);
console.log('runtime: matching, native cleanup, stale revision, pending lock, metadata checks passed');
