// Renderer acceptance on an ordinary HTTP fixture. No extension installation or browser permission UI.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,access,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
try{await access(resolve(root,'../../work/browser-test/browsers'));process.env.PLAYWRIGHT_BROWSERS_PATH ||= resolve(root,'../../work/browser-test/browsers');}catch{}
const {chromium}=await import('playwright');
const evidence=process.env.BROWSER_EVIDENCE_DIR||resolve(root,'../ui-acceptance');await mkdir(evidence,{recursive:true});
const server=createServer(async(req,res)=>{
  const name=new URL(req.url,'http://localhost').pathname.slice(1);
  if(!/^(?:[\w.-]+|icons\/icon-\d+\.png)$/.test(name)){res.writeHead(404);res.end();return;}
  try{const body=await readFile(resolve(root,'dist/extension',name));res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/html');res.end(name.endsWith('.html')?body.toString().replace('<head>', '<head><style>/* Simulate host extension font defaults; product body must override them. */ body { font-family: Arial, sans-serif; font-size: 75%; }</style>'):body);}catch{res.writeHead(404);res.end();}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const sample=`// ==UserScript==\n// @id example\n// @name 网页阅读助手\n// @version 1.0.0\n// @match https://example.com/*\n// ==/UserScript==\nWebMCPScript.install({id:'example',tools:[{name:'read_page',description:'读取页面标题',inputSchema:{type:'object',properties:{}},execute:()=>document.title}]});`;
let browser;const checks=[];const pass=name=>{checks.push(name);console.log('PASS',name);};
try{
  browser=await chromium.launch({channel:'chromium',headless:true});
  const context=await browser.newContext({viewport:{width:1280,height:820}});
  await context.addInitScript(({sample})=>{
    const first={id:'example',name:'网页阅读助手',version:'1.0.0',matches:['https://example.com/*'],source:sample,enabled:false};
    const native={id:1,url:'https://example.com/',title:'Example · 阅读页面',native:true,implementation:'native-0.4',tools:[{name:'website_search',description:'搜索当前网站的内容',source:{kind:'page'}}],errors:[]};
    window.fixture={scripts:[first],fail:false,mutations:0,pages:[native,{id:2,url:'https://unsupported.example/',title:'尚未支持 WebMCP',native:false,implementation:'native-0.4',tools:[]}]};
    Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(fixture.clipboardDenied)throw Error('denied');fixture.clipboard=text;}}});
    window.chrome={runtime:{getManifest:()=>({version:'0.3.0'}),getURL:p=>location.origin+'/'+p,sendMessage:async message=>{
      const f=window.fixture;
      if(message.type==='status')return {result:{scripts:structuredClone(f.scripts),port:17891,bridgeStatus:f.bridgeStatus||'已连接',userScriptsAvailable:f.userScriptsAvailable??true,lastError:''}};
      if(message.type==='pair'){if(f.fail)return {error:{message:'模拟连接保存失败'}};f.pair={token:message.token,port:message.port};f.bridgeStatus='连接中…';return {result:{ok:true}};}
      if(message.type==='pages')return {result:{pages:f.pages}};
      if(message.type==='inspect')return {result:f.pages[0]};
      if(message.type==='import'){
        if(f.fail)return {error:{message:'模拟保存失败：原有脚本已保留'}};
        try{const {prepareImport}=await import('/metadata.js');const script=prepareImport(message.source,f.scripts,message.replace,message.expectedSource,message.expectedEnabled);f.scripts=f.scripts.filter(s=>s.id!==script.id).concat(script);f.mutations++;return {result:{ok:true}};}catch(e){return {error:{message:e.message}};}
      }
      if(message.type==='toggle'){if(f.fail)return {error:{message:'模拟开关保存失败'}};f.scripts=f.scripts.map(s=>s.id===message.id?{...s,enabled:message.enabled}:s);return {result:{ok:true}};}
      if(message.type==='remove'){if(f.fail)return {error:{message:'模拟删除失败'}};f.scripts=f.scripts.filter(s=>s.id!==message.id);return {result:{ok:true}};}
      return {result:{ok:true}};
    }},tabs:{query:async()=>[{id:1,url:'https://example.com/'}],create:async tab=>{window.fixture.opened=tab.url;}}};
  },{sample});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin+'/manager.html');
  await page.locator('.brand img').waitFor();
  await page.waitForFunction(()=>document.querySelector('.brand img')?.naturalWidth===48);
  pass('dinosaur logo loads in manager at native 2x resolution');await page.getByRole('button',{name:'网页阅读助手',exact:true}).waitFor();
  const managerFonts=await page.evaluate(()=>Object.fromEntries(['html','body','.tab-rail a','.script-name','input[type=search]'].map(selector=>{const s=getComputedStyle(document.querySelector(selector));return [selector,{family:s.fontFamily,size:s.fontSize,lineHeight:s.lineHeight}];})));
  await writeFile(resolve(evidence,'manager-fonts.json'),JSON.stringify(managerFonts,null,2));
  await page.screenshot({path:resolve(evidence,'字体检查.png')});
  assert.equal(managerFonts.body.size,'13px');assert.equal(managerFonts.body.family,managerFonts.html.family);
  for(const selector of ['.tab-rail a','.script-name','input[type=search]'])assert.equal(managerFonts[selector].family,managerFonts.body.family);
  pass('extension body font defaults cannot override product typography');
  assert.equal(await page.locator('.app-header').evaluate(el=>el.getBoundingClientRect().height),48);
  assert.deepEqual(await page.locator('.tab-rail>a,.tab-rail>.new-tab').allTextContents(),['网页工具','已安装脚本','新建脚本','连接','设置']);
  assert.equal(await page.locator('#new-script').evaluate(el=>getComputedStyle(el).fontSize),'15px');
  assert.equal(await page.locator('.tab-rail>a').first().evaluate(el=>getComputedStyle(el).fontSize),'15px');
  assert.equal(await page.locator('.tab-rail').evaluate(el=>el.parentElement.className),'app-header');
  assert(await page.locator('#connection-label').isHidden());
  assert((await page.locator('#connection').getAttribute('aria-label')).includes('本地服务已连接'));
  await page.locator('#connection').click();await page.locator('#connection-settings').waitFor();
  await page.locator('a[href="#scripts"]').click();await page.locator('a[href="#scripts"][aria-current="page"]').waitFor();
  assert.equal(await page.locator('.app-header h1').innerText(),'');
  assert.equal(await page.locator('.app-header h1').getAttribute('aria-label'),'WebMCP Script');
  assert.equal(await page.locator('#new-script').evaluate(el=>getComputedStyle(el).borderTopWidth),'0px');
  assert.equal(await page.locator('#new-script').evaluate(el=>getComputedStyle(el,'::after').backgroundColor),'rgba(0, 0, 0, 0)');
  assert.equal(await page.locator('.tab-rail>a[aria-current=page]').evaluate(el=>getComputedStyle(el,'::after').backgroundColor),'rgb(78, 83, 91)');
  await page.evaluate(()=>fixture.bridgeStatus='连接断开，自动重连中');
  await page.locator('#connection-label').filter({hasText:'未连接'}).waitFor();
  assert((await page.locator('#connection').getAttribute('title')).includes('连接断开'));
  await page.locator('.app-header').screenshot({path:resolve(evidence,'单行顶栏-未连接.png')});
  await page.evaluate(()=>fixture.bridgeStatus='已连接');await page.locator('#connection-label').waitFor({state:'hidden'});
  await page.locator('.app-header').screenshot({path:resolve(evidence,'单行顶栏-已连接.png')});
  pass('48px primary navigation, 15px text, tools-first order, named new-script tab and quiet connection status');
  assert.equal(await page.locator('input[type=file]').count(),0);
  await page.screenshot({path:resolve(evidence,'脚本管理.png')});
  const enabledSwitch=page.getByRole('switch',{name:'启用 网页阅读助手',exact:true});
  assert.equal(await enabledSwitch.isChecked(),false);
  await enabledSwitch.focus();await page.keyboard.press('Space');
  await page.waitForFunction(()=>fixture.scripts[0].enabled);
  assert.equal(await enabledSwitch.isChecked(),true);
  await page.screenshot({path:resolve(evidence,'脚本启用.png')});
  await page.evaluate(()=>fixture.fail=true);await enabledSwitch.click();
  await page.locator('#error').filter({hasText:'模拟开关保存失败'}).waitFor();
  assert.equal(await enabledSwitch.isChecked(),true);
  assert.equal(await page.evaluate(()=>fixture.scripts[0].enabled),true);
  await page.evaluate(()=>fixture.fail=false);await enabledSwitch.uncheck();
  await page.waitForFunction(()=>!fixture.scripts[0].enabled);
  pass('named switch supports keyboard toggling and restores its state on failure');
  await page.getByRole('button',{name:'网页阅读助手',exact:true}).click();await page.locator('.cm-content').waitFor();
  assert(await page.locator('#save').isDisabled());pass('saved source opens in CodeMirror; save starts disabled; no file import control');
  // Drag within one line, then across lines: the active line must not cover the selection layer.
  const line=await page.locator('.cm-line').first().boundingBox();
  await page.mouse.move(line.x+18,line.y+line.height/2);await page.mouse.down();await page.mouse.move(line.x+140,line.y+line.height/2,{steps:8});await page.mouse.up();
  await page.locator('.cm-selectionBackground').first().waitFor();
  assert((await page.evaluate(()=>getSelection().toString())).length>0);
  const lineColor=await page.locator('.cm-activeLine').evaluate(el=>getComputedStyle(el).backgroundColor);
  assert(lineColor.startsWith('rgba(')&&Number(lineColor.match(/, ([\d.]+)\)$/)?.[1])<1,`active line must be translucent: ${lineColor}`);
  await page.screenshot({path:resolve(evidence,'单行选中.png')});
  // Start on a different row so rapid gestures are not interpreted as a double-click on Linux.
  const secondLine=await page.locator('.cm-line').nth(1).boundingBox();
  const thirdLine=await page.locator('.cm-line').nth(2).boundingBox();
  await page.mouse.move(secondLine.x+18,secondLine.y+secondLine.height/2);await page.mouse.down();await page.mouse.move(thirdLine.x+130,thirdLine.y+thirdLine.height/2,{steps:10});await page.mouse.up();
  assert((await page.evaluate(()=>getSelection().toString())).includes('\n'));await page.screenshot({path:resolve(evidence,'多行选中.png')});
  pass('single-line and multiline drag selection stay visible on the active line');
  const updated=sample.replace('1.0.0','1.1.0');
  await page.locator('.cm-content').fill(updated);await page.locator('#save:not([disabled])').waitFor();
  await page.locator('a[href="#scripts"]').click();await page.locator('a[href="#scripts"][aria-current="page"]').waitFor();await page.locator('a[href="#editor"]').click();await page.locator('a[href="#editor"][aria-current="page"]').waitFor();assert((await page.locator('.cm-content').innerText()).includes('1.1.0'));pass('draft survives tab switching');
  await page.locator('#save').click();await page.locator('#preview-dialog[open]').waitFor();assert.equal(await page.evaluate(()=>fixture.mutations),0);assert.equal(await page.locator('#preview-state').innerText(),'保留停用状态');
  await page.locator('#cancel-save').click();assert.equal(await page.evaluate(()=>fixture.mutations),0);
  await page.locator('#save').click();await page.locator('#confirm-save').click();await page.locator('#preview-dialog').waitFor({state:'hidden'});await page.locator('#save:disabled').waitFor();
  assert.equal(await page.evaluate(()=>fixture.scripts[0].enabled),false);assert.equal(await page.evaluate(()=>fixture.scripts[0].previousSource),sample);pass('cancel has no mutation; confirmed save preserves disabled state and previous revision');
  await page.locator('.cm-content').fill(updated+'\n// 未保存的修改');await page.locator('#save:not([disabled])').waitFor();
  await page.evaluate(()=>fixture.fail=true);await page.locator('#save').click();await page.locator('#confirm-save').click();await page.locator('#preview-error:not([hidden])').waitFor();
  assert((await page.locator('.cm-content').innerText()).includes('未保存的修改'));assert.equal(await page.evaluate(()=>fixture.scripts[0].source),updated);
  await page.locator('#cancel-save').click();await page.evaluate(()=>fixture.fail=false);pass('save error preserves both draft and saved revision');
  await page.evaluate(()=>fixture.scripts[0].source+='\n// changed elsewhere');
  await page.locator('.cm-content').focus();await page.keyboard.press(process.platform==='darwin'?'Meta+s':'Control+s');await page.locator('#preview-dialog[open]').waitFor();await page.locator('#confirm-save').click();await page.locator('#preview-error:not([hidden])').waitFor();assert((await page.locator('#preview-error').innerText()).includes('其他窗口'));await page.locator('#cancel-save').click();await page.evaluate(source=>fixture.scripts[0].source=source,updated);pass('save shortcut works; concurrent source change is rejected');
  await page.locator('.menu summary').first().click();await page.locator('#find').evaluate(e=>e.closest('details').open=true);await page.locator('#find').click();await page.locator('.cm-search').waitFor();pass('CodeMirror native search panel opens');
  await page.locator('.cm-search button[name=close]').click();
  await page.locator('.cm-scroller').evaluate(el=>{el.scrollLeft=0;el.scrollTop=0;});
  await page.screenshot({path:resolve(evidence,'脚本编辑.png')});
  await page.locator('.menu summary').first().click();page.once('dialog',d=>d.accept());await page.locator('#restore').click();await page.locator('#preview-dialog[open]').waitFor();await page.locator('#confirm-save').click();await page.locator('#preview-dialog').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>fixture.scripts[0].source),sample);assert.equal(await page.evaluate(()=>fixture.scripts[0].enabled),false);pass('file menu restore uses preview and preserves disabled state');
  await page.locator('.cm-content').fill(updated+'\n// 未保存的修改');
  page.once('dialog',d=>d.dismiss());await page.locator('#close-editor').click();assert(await page.locator('#editor-tab').isVisible());
  page.once('dialog',d=>d.accept());await page.locator('#close-editor').click();await page.locator('#editor-tab').waitFor({state:'hidden'});pass('closing a dirty editor requires discard confirmation');
  await page.locator('#new-script').click();await page.locator('.cm-content').waitFor();
  assert.equal(await page.locator('#new-script').getAttribute('aria-current'),'page');assert(await page.locator('#editor-tab').isHidden());
  assert.equal(await page.locator('#new-script').evaluate(el=>getComputedStyle(el,'::after').backgroundColor),'rgb(78, 83, 91)');
  const template=await page.locator('.cm-content').innerText();assert(template.includes('// ==UserScript=='));assert(template.includes('document.modelContext.registerTool'));assert(!template.includes('WebMCPScript'));assert(template.includes('https://example.com/*'));
  await page.screenshot({path:resolve(evidence,'新建脚本.png')});
  await page.locator('.cm-content').fill(template+'\n// 保留新建草稿');
  await page.locator('a[href="#scripts"]').click();await page.locator('a[href="#scripts"][aria-current="page"]').waitFor();assert.equal(await page.locator('#new-script').getAttribute('aria-current'),null);await page.locator('#new-script').click();
  assert((await page.locator('.cm-content').innerText()).includes('保留新建草稿'));await page.locator('#new-script').click();assert((await page.locator('.cm-content').innerText()).includes('保留新建草稿'));assert(await page.locator('#editor-tab').isHidden());
  pass('plus is the selected editor tab; template and draft survive repeated selection without a new tab');
  const fresh=sample.replaceAll('example','reading').replace('网页阅读助手','新脚本');await page.locator('.cm-content').fill(fresh);await page.locator('#save').click();await page.locator('#confirm-save').click();await page.locator('#preview-dialog').waitFor({state:'hidden'});await page.locator('#save:disabled').waitFor();assert.equal(await page.evaluate(()=>fixture.scripts.length),2);assert(await page.locator('#editor-tab').isHidden());assert.equal(await page.locator('#new-script').getAttribute('aria-current'),'page');pass('plus tab → paste full source → preview → save creates a script without adding a tab');
  await page.locator('a[href="#pages"]').click();await page.locator('a[href="#pages"][aria-current="page"]').waitFor();assert((await page.locator('#page-list').innerText()).includes('浏览器未提供原生 WebMCP 接口'));await page.locator('#page-list details').first().locator('summary').click();assert((await page.locator('#page-list').innerText()).includes('website_search'));await page.screenshot({path:resolve(evidence,'网页工具.png')});pass('native website tool displayed; unsupported state is distinct from zero tools');
  await page.locator('a[href="#scripts"]').click();await page.locator('a[href="#scripts"][aria-current="page"]').waitFor();await page.locator('#search').fill('missing');await page.locator('#empty-action').click();assert.equal(await page.locator('#script-rows tr').count(),2);
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve(evidence,'窄屏管理.png')});pass('empty search clears; 390px viewport has no document overflow');
  const popup=await context.newPage();await popup.setViewportSize({width:344,height:600});await popup.goto(origin+'/popup.html');await popup.locator('#tool-count').filter({hasText:'1'}).waitFor();const popupFonts=await popup.evaluate(()=>{const s=getComputedStyle(document.body);return {family:s.fontFamily,size:s.fontSize};});assert.deepEqual(popupFonts,{family:managerFonts.body.family,size:'13px'});assert.equal(await popup.locator('#scripts input[type=checkbox]').count(),1);
  assert.equal(await popup.locator('#script-group').evaluate(el=>el.open),false);assert(await popup.locator('#new-script').isHidden());
  assert.equal(await popup.locator('#script-count').innerText(),'1');
  await popup.locator('body').screenshot({path:resolve(evidence,'插件弹窗.png')});
  await popup.locator('#script-group>summary').focus();await popup.keyboard.press('Space');assert(await popup.locator('#new-script').isVisible());
  await popup.locator('.popup-script summary').click();await popup.locator('#scripts input').check();assert.equal(await popup.evaluate(()=>fixture.scripts[0].enabled),true);pass('popup shows current native tools and matching script toggle');
  assert.equal(await popup.locator('h1,#domain,.popup-title').count(),0);
  assert.equal(await popup.locator('#connection').innerText(),'已连接');
  await popup.evaluate(()=>fixture.scripts[0].name='网页阅读助手 · 一个很长的脚本名称');
  await popup.getByRole('checkbox').uncheck();await popup.getByRole('checkbox').check();
  const scriptLabel=popup.locator('.popup-script-name');assert((await scriptLabel.getAttribute('title')).includes('一个很长的脚本名称'));
  assert.equal(await scriptLabel.evaluate(el=>getComputedStyle(el).textOverflow),'ellipsis');
  assert(await popup.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.equal(await popup.getByRole('switch').count(),0);
  assert(await popup.getByText('website_search',{exact:true}).isVisible());
  assert(await popup.getByText('页面提供',{exact:true}).isVisible());
  await popup.evaluate(()=>fixture.pages[0].tools.push({name:'script_read',source:{kind:'script',id:'example',name:'网页阅读助手'}}));
  await popup.getByRole('checkbox').uncheck();
  assert(await popup.getByText('脚本 · 网页阅读助手',{exact:true}).isVisible());
  await popup.evaluate(()=>fixture.pages[0].tools.pop());await popup.getByRole('checkbox').check();
  assert(await popup.locator('#tools').evaluate(el=>el.getBoundingClientRect().top<document.querySelector('#scripts').getBoundingClientRect().top));
  assert.equal(await popup.locator('#connect').evaluate(el=>el.parentElement.id),'popup-footer');
  await popup.locator('#tools summary').click();assert(await popup.getByText('website_search',{exact:true}).isHidden());await popup.locator('#tools summary').click();
  await popup.evaluate(()=>fixture.bridgeStatus='连接断开，自动重连中');await popup.getByRole('checkbox').uncheck();
  assert.equal(await popup.locator('#connection').innerText(),'未连接');assert((await popup.locator('#connect').getAttribute('title')).includes('连接断开'));
  assert.equal(await popup.locator('#connect').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(233, 240, 250)');
  assert(await popup.locator('#connect').evaluate(el=>el.getBoundingClientRect().top<document.querySelector('#tools').getBoundingClientRect().top));
  await popup.locator('body').screenshot({path:resolve(evidence,'弹窗未连接.png')});
  await popup.evaluate(()=>{window.close=()=>{fixture.closed=true;};});await popup.locator('#connect').click();
  assert((await popup.evaluate(()=>fixture.opened)).endsWith('manager.html#connection-settings'));assert.equal(await popup.evaluate(()=>fixture.closed),true);
  pass('tools come first and start expanded; connection sits in footer until disconnected; compact names and settings link work');
  await popup.evaluate(()=>fixture.bridgeStatus='已连接');await popup.getByRole('checkbox').check();
  await popup.evaluate(()=>{fixture.savedTools=fixture.pages[0].tools;fixture.pages[0].tools=['read','prepare','execute'].map(s=>({name:'example_config_'+s}));});
  await popup.getByRole('checkbox').uncheck();
  assert.equal(await popup.getByText('刷新网页后可查看工具来源',{exact:true}).count(),0);
  assert.equal(await popup.locator('#tool-list ul>li').count(),3);
  assert.equal(await popup.getByText('来源未确认',{exact:true}).count(),0);
  await popup.locator('body').screenshot({path:resolve(evidence,'弹窗-无来源.png')});
  await popup.evaluate(()=>{for(const tool of fixture.pages[0].tools)tool.source={kind:'script',id:'example',name:'网页阅读助手'};});
  await popup.getByRole('checkbox').check();
  assert.equal(await popup.getByText('脚本 · 网页阅读助手',{exact:true}).count(),1);
  assert.equal(await popup.locator('#tool-list ul>li').count(),3);
  assert.equal(await popup.locator('#tools>summary>svg').count(),2);
  const editButton=popup.getByRole('button',{name:'编辑',exact:true});await editButton.hover();
  assert.equal(await editButton.evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(241, 241, 241)');
  assert.equal(await editButton.locator('svg').count(),1);
  await popup.locator('body').screenshot({path:resolve(evidence,'弹窗-来源分组.png')});
  await popup.evaluate(()=>{fixture.pages[0].tools=fixture.savedTools;});await popup.getByRole('checkbox').uncheck();await popup.getByRole('checkbox').check();
  pass('Chrome-style SVG icons, gray hover, blue connection prompt, grouped sources and omitted unknown sources');
  const scriptSummary=popup.locator('.popup-script summary');await scriptSummary.click();await scriptSummary.focus();await popup.keyboard.press('Space');
  await popup.locator('.popup-script details[open]').waitFor();assert.equal(await popup.getByRole('checkbox').isChecked(),true);
  await popup.getByRole('checkbox').uncheck();assert(await popup.getByRole('button',{name:'编辑',exact:true}).isVisible());
  await popup.getByRole('checkbox').check();
  assert(await popup.getByText('已启用',{exact:true}).isVisible());
  await popup.evaluate(()=>fixture.fail=true);await popup.getByRole('checkbox').click();await popup.locator('#error').filter({hasText:'模拟开关保存失败'}).waitFor();assert(await popup.getByRole('checkbox').isChecked());await popup.evaluate(()=>fixture.fail=false);await popup.getByRole('checkbox').uncheck();await popup.getByRole('checkbox').check();
  await popup.locator('body').screenshot({path:resolve(evidence,'脚本操作菜单.png')});
  await popup.getByRole('button',{name:'编辑',exact:true}).click();
  const editURL=await popup.evaluate(()=>fixture.opened);assert(editURL.endsWith('manager.html#edit/example'));
  const editPage=await context.newPage();await editPage.goto(editURL);await editPage.locator('.cm-content').waitFor();
  assert.equal(await editPage.locator('#filename').innerText(),'example.user.js');assert((await editPage.locator('.cm-content').innerText()).includes('@id example'));
  await editPage.locator('.cm-content').fill(sample+'\n// preserve draft');
  await editPage.evaluate(source=>fixture.scripts.push({...fixture.scripts[0],id:'second',name:'Second',source}),sample.replaceAll('example','second'));
  editPage.once('dialog',dialog=>dialog.dismiss());await editPage.evaluate(()=>location.hash='edit/second');
  await editPage.waitForFunction(()=>location.hash==='#editor');assert((await editPage.locator('.cm-content').innerText()).includes('preserve draft'));
  await editPage.close();
  const missingPage=await context.newPage();await missingPage.goto(origin+'/manager.html#edit/missing');await missingPage.locator('#error').filter({hasText:'脚本不存在或已删除'}).waitFor();await missingPage.close();
  popup.once('dialog',dialog=>dialog.dismiss());await popup.getByRole('button',{name:'删除',exact:true}).click();assert.equal(await popup.evaluate(()=>fixture.scripts.length),1);
  await popup.evaluate(()=>fixture.fail=true);popup.once('dialog',dialog=>dialog.accept());await popup.getByRole('button',{name:'删除',exact:true}).click();
  await popup.locator('#error').filter({hasText:'模拟删除失败'}).waitFor();assert.equal(await popup.locator('.popup-script').count(),1);
  await popup.evaluate(()=>fixture.fail=false);popup.once('dialog',dialog=>dialog.accept());await popup.getByRole('button',{name:'删除',exact:true}).click();
  await popup.getByText('本页无匹配脚本',{exact:true}).waitFor();assert.equal(await popup.evaluate(()=>fixture.scripts.length),0);
  assert.equal(await popup.locator('#script-count').innerText(),'0');assert(await popup.locator('#new-script').isVisible());
  await popup.locator('#new-script').click();assert((await popup.evaluate(()=>fixture.opened)).endsWith('manager.html#new'));
  const newPage=await context.newPage();await newPage.goto(origin+'/manager.html#new');await newPage.locator('.cm-content').waitFor();assert((await newPage.locator('.cm-content').innerText()).includes('document.modelContext.registerTool'));await newPage.close();
  pass('A layout: collapsed scripts, nested new action available even when empty, checkbox menu, direct editor and deletion recovery');
  await page.setViewportSize({width:1280,height:820});
  // Create a fresh draft through the visible file menu in the editor.
  await page.locator('#new-script').click();await page.locator('.menu summary').first().click();await page.locator('#file-new').click();
  const standard=sample.replace('// @id example\n','// @namespace copied-userscript\n').replace('@match https://example.com/*','@match [https://example.com/*](https://example.com/*)').replace(/WebMCPScript\.install[\s\S]*/,"document.modelContext.registerTool({name:'copied_tool',description:'Read title',inputSchema:{type:'object',properties:{}},execute:()=>document.title});");
  await page.locator('.cm-content').fill(standard);await page.locator('#save').click();await page.locator('#preview-dialog[open]').waitFor();assert.equal(await page.locator('#preview-matches').innerText(),'https://example.com/*');await page.locator('#confirm-save').click();await page.locator('#preview-dialog').waitFor({state:'hidden'});
  assert(!(await page.locator('.cm-content').innerText()).includes('@match ['));assert.equal(await page.evaluate(()=>fixture.scripts.find(s=>s.namespace==='copied-userscript').matches[0]),'https://example.com/*');
  pass('pasted native userscript needs no id; link-form match is normalized in preview, storage and editor');
  await page.locator('a[href="#scripts"]').click();await page.locator('a[href="#scripts"][aria-current="page"]').waitFor();
  await page.locator('table').waitFor({state:'visible'});
  const tableTop=await page.locator('table').evaluate(el=>el.getBoundingClientRect().top);
  page.once('dialog',dialog=>dialog.accept());await page.locator('[data-script-id=example]').getByRole('button',{name:'卸载'}).click();await page.locator('#notice').waitFor();
  assert.equal(await page.locator('#notice').evaluate(el=>getComputedStyle(el).position),'fixed');
  assert.equal(await page.locator('table').evaluate(el=>el.getBoundingClientRect().top),tableTop);
  await page.screenshot({path:resolve(evidence,'轻提示.png')});
  await page.locator('#notice').waitFor({state:'hidden',timeout:5000});
  assert.equal(await page.locator('table').evaluate(el=>el.getBoundingClientRect().top),tableTop);
  pass('uninstall feedback floats outside layout and disappears automatically');
  await page.evaluate(()=>{fixture.bridgeStatus='未配对';window.dispatchEvent(new Event('focus'));});
  await page.locator('a[href="#connection-settings"]').click();await page.locator('a[href="#connection-settings"][aria-current="page"]').waitFor();
  await page.locator('#connection-state').filter({hasText:'尚未连接'}).waitFor();
  assert(!(await page.locator('#manual-connection').getAttribute('open')));
  await page.locator('#copy-connection:enabled').waitFor();await page.locator('#copy-connection').click();
  const instructions=await page.evaluate(()=>fixture.clipboard);
  assert(instructions.includes('connection_info'));assert(instructions.includes(root));assert(!instructions.includes('.local/pairing-token'));
  const config=JSON.parse(await page.locator('#mcp-config').inputValue());
  assert.equal(config.mcpServers['webmcp-script'].command,process.execPath);
  assert(!JSON.stringify(config).includes('WEBMCP_TOKEN'));
  await page.screenshot({path:resolve(evidence,'连接引导.png')});
  await page.evaluate(()=>fixture.clipboardDenied=true);await page.locator('#copy-connection').click();
  assert(await page.locator('#connection-copy-fallback').isVisible());assert.equal(await page.locator('#connection-copy-fallback').inputValue(),instructions);
  await page.evaluate(()=>fixture.clipboardDenied=false);await page.locator('#copy-connection').click();
  assert(await page.locator('#connection-copy-fallback').isHidden());
  await page.locator('#token').fill('不完整');await page.locator('#pair').click();await page.locator('#pair-error:not([hidden])').waitFor();
  assert.equal(await page.evaluate(()=>fixture.pair),undefined);assert.equal(await page.locator('#token').inputValue(),'不完整');
  const pairingCode=JSON.stringify({version:1,token:'a'.repeat(64),port:17999});
  await page.locator('#token').fill(pairingCode);await page.evaluate(()=>fixture.fail=true);await page.locator('#pair').click();
  await page.locator('#pair-error').filter({hasText:'模拟连接保存失败'}).waitFor();assert.equal(await page.locator('#token').inputValue(),pairingCode);
  await page.evaluate(()=>fixture.fail=false);await page.locator('#pair').click();
  await page.locator('#connection-state').filter({hasText:'正在连接'}).waitFor();assert.equal(await page.evaluate(()=>fixture.pair.port),17999);assert.equal(await page.locator('#token').inputValue(),'');
  await page.evaluate(()=>{fixture.bridgeStatus='已连接';window.dispatchEvent(new Event('focus'));});
  await page.locator('#connection-state').filter({hasText:'浏览器已连接'}).waitFor();assert((await page.locator('#connection-next').innerText()).includes('完成连接验证'));
  await page.screenshot({path:resolve(evidence,'连接成功.png')});
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:resolve(evidence,'窄屏连接.png')});
  pass('guided connection: real local config, clipboard fallback, validation, embedded port, failure recovery and honest connected state');
  await context.route('**/connection-config.json',route=>route.fulfill({contentType:'application/json',body:'null'}));
  const portable=await context.newPage();await portable.setViewportSize({width:390,height:844});
  await portable.goto(origin+'/manager.html#connection-settings');
  await portable.locator('#copy-connection:enabled').click();
  const portableInstructions=await portable.evaluate(()=>fixture.clipboard);
  assert(portableInstructions.includes('node setup.mjs'));assert(!portableInstructions.includes(root));
  assert(await portable.locator('#copy-config').isDisabled());
  await portable.getByText('连接检查',{exact:true}).click();await portable.locator('#check-connection').click();
  await portable.locator('#connection-checks').filter({hasText:'1 / 2'}).waitFor();
  assert((await portable.locator('#connection-checks').innerText()).includes('仍需让 AI 调用 pages'));
  await portable.evaluate(()=>{fixture.userScriptsAvailable=false;fixture.bridgeStatus='未配对';});
  await portable.locator('#check-connection').click();await portable.locator('#connection-checks').filter({hasText:'尚未配对'}).waitFor();
  assert((await portable.locator('#connection-checks').innerText()).includes('允许用户脚本'));
  assert.equal(await portable.evaluate(()=>fixture.mutations),0);
  assert(await portable.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await portable.screenshot({path:resolve(evidence,'预构建连接检查.png')});await portable.close();
  pass('portable setup instructions contain no publisher path; connection checks explain permissions, relay and native support without mutations');
  assert.deepEqual(errors,[]);
  await writeFile(resolve(evidence,'result.json'),JSON.stringify({boundary:'HTTP renderer fixture with mocked Chrome messaging; not installed-extension acceptance',browser:browser.version(),checks},null,2));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
