import assert from 'node:assert/strict';
import {compareVersions,digest,fetchScript,inspectUpdate,updateSettings,validateSyntax} from '../extension/updates.js';
import {parseScript,prepareImport} from '../extension/metadata.js';
const source=(version='1.0.0',extra='',body='globalThis.neverRun = true;')=>`// ==UserScript==\n// @id updater\n// @name Updater\n// @version ${version}\n// @match https://example.com/*\n${extra}\n// ==/UserScript==\n${body}`;
for(const [a,b,expected] of [['1.10','1.9',1],['1.0','1',0],['2','10',-1],['1.0.0-beta.10','1.0.0-beta.2',1],['1.0','1.0-rc.1',1],['1.0+a','1.0+b',0],['1.0-a.1','1.0-a.1.1',-1],['1.0-1','1.0-a',-1]])assert.equal(compareVersions(a,b),expected);
assert.throws(()=>compareVersions('latest','1'),/版本格式/);
validateSyntax(source());assert.equal(globalThis.neverRun,undefined);
for(const invalid of ['const = ;','const a=1; const a=2;','break;','await fetch("/");'])assert.throws(()=>validateSyntax(source('2','',invalid)),/语法/);
for(const url of ['http://example.com/a','https://a:b@example.com/a','https://example.com/a#hash'])await assert.rejects(fetchScript(url,()=>assert.fail('fetch must not run')),/HTTPS/);
await assert.rejects(fetchScript('https://example.com/a',async()=>new Response('login',{headers:{'content-type':'text/html'}})),/登录页/);
await assert.rejects(fetchScript('https://example.com/a',async()=>new Response('x'.repeat(1024*1024+1))),/1 MB/);
await assert.rejects(fetchScript('https://example.com/a',async()=>new Response(null,{status:302,headers:{location:'https://other.example/a'}})),/跨站/);
const original=parseScript(source()),remote=source('2');
assert.equal((await inspectUpdate(original,()=>assert.fail('no URL'))).status,'no-source');
assert.equal(updateSettings(parseScript(source('1','// @updateURL none'))).downloadURL,'');
original.updates={mode:'auto',updateURL:'https://example.com/a',downloadURL:'https://example.com/a',baselineSha256:await digest(original.source)};
let downloaded=remote;
const fetcher=async(url,options)=>{assert.equal(options.credentials,'omit');assert.equal(options.redirect,'manual');assert.equal(options.referrerPolicy,'no-referrer');return new Response(downloaded);};
assert.deepEqual((await inspectUpdate(original,fetcher)).reasons,[]);
const local=prepareImport(original.source+'\n// local edit',[original],original.id,original.source);
assert.equal(local.updates,original.updates);
assert.match((await inspectUpdate(local,fetcher)).reasons.join(),/本地源码/);
downloaded=remote.replace('example.com/*','*.example.com/*');assert.match((await inspectUpdate(original,fetcher)).reasons.join(),/网站范围/);
downloaded=source('2','// @downloadURL https://other.example/a');assert.match((await inspectUpdate(original,fetcher)).reasons.join(),/来源变化/);
downloaded=original.source;assert.equal((await inspectUpdate(original,fetcher)).status,'current');
downloaded=original.source+'\n// changed';assert.equal((await inspectUpdate(original,fetcher)).status,'same-version-changed');
downloaded=source('0.1');assert.equal((await inspectUpdate(original,fetcher)).status,'older');
downloaded=remote.replace('@id updater','@id other');await assert.rejects(inspectUpdate(original,fetcher),/ID/);
original.updates.downloadURL='https://example.com/download';
await assert.rejects(inspectUpdate(original,async url=>new Response(url.endsWith('download')?source('3'):source('2'))),/版本不一致/);
console.log('updates: version ordering, no execution, transport limits, local edits, scope/source guards and metadata consistency checked');
